### PR TITLE
Install iptables required by kubernetes-mesos's proxy process

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by karlkfi** [comment]
Hope we can get this in. not sure who to ask...

Nits:
- I usually do an apt-get clean after installing anything in docker to reduce the image size (cleans up artifacts).

**Comment by ssk2** [comment]
@karlkfi - if you can test and verify this works well, feel free to merge. I can give you the credentials to push to Docker Hub.

**Comment by ssk2** [comment]
Oh it's just one package.

**Comment by cmaloney** [comment]
I don't think installing more stuff in our base images makes sense here unless it's required by mesos. Just making a new dockerfile which builds upon mesos-slave would be much cleaner (And give you exactly the same result)

**Comment by ssk2** [comment]
Ah, that's fair.

**Comment by BenWhitehead** [comment]
@ssk2 @karlkfi please don't do manual pushes to docker hub, setup a build in teamcity to do it for you.  There is already a template, just point it to the code and tell it the docker image to push to.

**Comment by karlkfi** [comment]
Sounds like there are reservations about pulling this into the Mesos image when mesos itself doesn't use it. So I'll make a new image that wraps this one, specifically for kubernetes on mesos. It's unfortunate that kubernetes needs a special dependencies on the mesos host. We may have to consider installing them on demand or some other proxying solution.

**Pull request merged**
